spring:
  application:
    name: ai-worker-service
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:demo}
      chat:
        options:
          model: gpt-4-turbo-preview

server:
  port: 8082
