global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'doc-core-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['doc-core-service:8080']

  - job_name: 'ai-worker-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ai-worker-service:8081']
