spring:
  application:
    name: doc-core-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/docgen
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/DocGenRealm
          jwk-set-uri: http://localhost:8080/realms/DocGenRealm/protocol/openid-connect/certs

server:
  port: 8081
